#! /usr/bin/env bash

if [ -z "$1" ]; then
  echo
  echo "Usage: ./install_in_fherma_cifar [path to deps directory]"
  echo
  exit -1
fi

cmake -B build -DCMAKE_INSTALL_PREFIX=$1 -DCMAKE_POSITION_INDEPENDENT_CODE=ON -G Ninja
cmake --build build -j --config Release
cmake --install build --config Release

